# Generated by Django 4.2 on 2023-04-28 10:21

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название категории")),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("description", models.TextField(max_length=300, verbose_name="Описание категории")),
                ("post_amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("short_description", models.TextField(max_length=300, null=True, verbose_name="Краткое описание")),
                ("body", ckeditor.fields.RichTextField(verbose_name="Описание")),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("post_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/media/post_image",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "webp", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_post",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="blog.category")),
                ("likes", models.ManyToManyField(blank=True, related_name="post_likes", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
