# Generated by Django 4.2 on 2023-04-28 11:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, unique=True, verbose_name="Персональная ссылка"),
                ),
                ("bio", models.TextField(blank=True, max_length=500, verbose_name="Информация о себе")),
                ("date_birthday", models.DateField(blank=True, null=True, verbose_name="Дата рождения")),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_profile/media/user_image",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "webp", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "follows",
                    models.ManyToManyField(
                        blank=True, related_name="followed_by", to="user_profile.profile", verbose_name="Подписки"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Профиль пользователя",
                    ),
                ),
            ],
        ),
    ]
